version: 2
jobs:
  build:
    macos:
      xcode: "11.7"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - restore_cache:
          keys:
          - macos-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum ".circleci/config.yml" }}
          - macos-dependencies-{{ checksum "Gemfile.lock" }}
          - macos-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: macos-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              spec/
      - store_test_results:
          path: /tmp/test-results
